name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose the appropriate Python version
     
    - name: see the file structure
      run: ls

    - name: Install dependencies
      run: pip install -r hyd-test/requirement.txt

    - name: Start Flask server
      run: python hyd-test/htmlapp.py &

    - name: Wait for server to start
      run: sleep 5


